"""Canonical enums for SITLA Intelligence."""

from __future__ import annotations

OPPORTUNITY_TYPES = [
    "COMPETITIVE_MINERAL_LEASE",
    "OIL_GAS_MINERAL_LEASE",
    "METALLIFEROUS_MINERAL_LEASE",
    "INDUSTRIAL_MINERAL_LEASE",
    "MINERAL_MATERIAL_PERMIT",
    "SAND_GRAVEL_PERMIT",
    "COAL_LEASE",
    "HELIUM_LEASE",
    "LITHIUM_LEASE",
    "POTASH_LEASE",
    "PHOSPHATE_LEASE",
    "GEOTHERMAL_ARRANGEMENT",
    "OTHER_BUSINESS_ARRANGEMENT",
    "COMPETING_APPLICATION_NOTICE",
    "LAND_NOMINATION",
    "REOFFERING",
    "SURFACE_SALE_MINERAL_RELEVANT",
    "UNKNOWN",
]

LIFECYCLE_STATUSES = [
    "DISCOVERED",
    "ANNOUNCED",
    "NOMINATION_OPEN",
    "NOMINATED",
    "PUBLIC_NOTICE_OPEN",
    "COMPETING_APPLICATION_OPEN",
    "SCHEDULED",
    "BIDDING_OPEN",
    "BIDDING_CLOSED",
    "UNDER_REVIEW",
    "AWARDED",
    "LEASE_EXECUTION_PENDING",
    "LEASE_ACTIVE",
    "NO_BID",
    "NOT_AWARDED",
    "WITHDRAWN",
    "CANCELLED",
    "EXPIRED",
    "REOFFERED",
    "ARCHIVED",
    "UNKNOWN",
]

ACTIVE_LIFECYCLE = {
    "DISCOVERED",
    "ANNOUNCED",
    "NOMINATION_OPEN",
    "NOMINATED",
    "PUBLIC_NOTICE_OPEN",
    "COMPETING_APPLICATION_OPEN",
    "SCHEDULED",
    "BIDDING_OPEN",
    "UNDER_REVIEW",
    "LEASE_EXECUTION_PENDING",
    "UNKNOWN",
}

SOURCE_HEALTH = [
    "HEALTHY",
    "DEGRADED",
    "STALE",
    "FAILED",
    "MANUAL",
    "DISABLED",
    "UNCONFIGURED",
]

PRIORITY_TIERS = ["A", "B", "C", "D", "E"]
