"""Normalized enums for Tax Sales intelligence."""

from __future__ import annotations

SALE_LIFECYCLE_STATUSES = [
    "DISCOVERED",
    "DELINQUENT",
    "SALE_ELIGIBLE",
    "PENDING_TAX_DEED",
    "TAX_DEED_ISSUED",
    "COUNTY_OR_TRUSTEE_HELD",
    "NOTICE_PUBLISHED",
    "AUCTION_SCHEDULED",
    "AUCTION_ACTIVE",
    "REDEEMED",
    "WITHDRAWN",
    "NO_BID",
    "SOLD",
    "RECONVEYED",
    "CANCELLED",
    "UNKNOWN",
]

PUBLICATION_SCOPES = [
    "ALL_UNPAID",
    "DELINQUENT_SUBSET",
    "SALE_ELIGIBLE_ONLY",
    "PENDING_TAX_DEED",
    "TAX_DEEDED_ONLY",
    "TRUST_INVENTORY",
    "AUCTION_ONLY",
    "RESULTS_ONLY",
    "MANUAL_UPLOAD_ONLY",
    "UNKNOWN",
]

PATENT_CLASSIFICATIONS = [
    "CONFIRMED",
    "PROBABLE",
    "POSSIBLE",
    "UNLIKELY",
    "CONTRADICTED",
    "UNKNOWN",
]

MINERAL_SIGNALS = ["HIGH", "MEDIUM", "LOW", "UNKNOWN"]

ACCESS_STATUSES = [
    "APPARENT_PUBLIC_ACCESS",
    "APPARENT_ROAD_CONTACT",
    "POSSIBLE_PRIVATE_ACCESS",
    "NO_APPARENT_MAPPED_ACCESS",
    "LANDLOCKED_INDICATOR",
    "UNKNOWN",
]

PRIORITY_TIERS = ["A", "B", "C", "D", "E"]

SOURCE_HEALTH = [
    "HEALTHY",
    "DEGRADED",
    "STALE",
    "FAILED",
    "MANUAL",
    "DISABLED",
    "UNCONFIGURED",
]

ACTIVE_LIFECYCLE = {
    "DISCOVERED",
    "DELINQUENT",
    "SALE_ELIGIBLE",
    "PENDING_TAX_DEED",
    "TAX_DEED_ISSUED",
    "COUNTY_OR_TRUSTEE_HELD",
    "NOTICE_PUBLISHED",
    "AUCTION_SCHEDULED",
    "AUCTION_ACTIVE",
    "NO_BID",
    "UNKNOWN",
}
